### ISSUE TITLE
Minor bug: "GeoIP Detection: No database installed" notice is shown to subscribers (non-admin) users

### ISSUE THREAD

**Issue by meitar** [yellowtree/wp-geoip-detect#22]
* WordPress version: 4.4.1
* GeoIP Detect version: 2.5.4

# Description

Despite dismissing the "GeoIP Detection: No database installed" admin notice as an administrator user (i.e., requesting that the notice not be displayed again), when I logged into the site in which the plugin was installed as a user assigned the `Subscriber` role, the same admin notice reappeared.

# Steps to reproduce

1. Install GeoIP Detection plugin as a user assigned the `Administrator` role.
1. After installation, click the textual "Dismiss" link at the top-right of the "No database installed" admin notice that appears.
1. Log out of WordPress and log back into WordPress as a user assigned the `Subscriber` role.
1. Observe the "No database installed" admin notice has reappeared.

# Expected results

I expected that this particular admin notice never appear for a Subscriber because they do not have a relevant role in managing the GeoIP database for the site.

Barring that, I expected that clicking the "Dismiss" link in the admin notice would prevent the notice from being shown again regardless of the currently logged-in user.

# Actual results

Logging into other user accounts, apparently regardless of the capabilities those user accounts have, display the admin notice again.

**Comment by benjaminpick** [comment]
Hi,

yes the current behavior is user-specific. I thought this makes some
sense because different users are normally different admins which should
all know that there is a problem.

The real question is which capability is necessary to show this message.
You're right, subscriber shouldn't see it at all. Probably the best is
to use 'manage_options' as without this capability, changing the
datasource won't work anyway. (see /admin-ui.php, line 8)
