### ISSUE TITLE
Nearest location

### ISSUE THREAD

**Issue by scooterbelasco** [yellowtree/wp-geoip-detect#26]
Trying to use the latitude/longitude to calculate the nearest location and present the user with content- in this case a phone number. Can anyone help me out?

Locations:
`var officeLocations = {
   "Philadelphia": {latitude: 39.952115, longitude: -75.163696},
   "Los Angeles": {latitude: 34.052853, longitude: -118.240077},
   "Sydney": {latitude: -24.952110, longitude: 133.370889}
}
var officePhoneNumbers = {
   "Philadelphia": "1111111111",
   "Los Angeles": "2134453245",
   "Sydney": "1454377643543"
}`

I've got the call set up and working as follows:
`function geoip_phonenumber(){
    $userInfo = geoip_detect2_get_info_from_current_ip();
    $lat = $userInfo->location->latitude;
    $lon = $userInfo->location->longitude;
    if ($lat) {
?>

<script>
document.getElementById("phonenumber").innerHTML = <?php echo json_encode($lon) ?>;
</script>

<?php
    }
}`

Much appreciated!

**Comment by benjaminpick** [comment]
Things to get you started:

Calculating the distance:
> https://stackoverflow.com/questions/27928/calculate-distance-between-two-latitude-longitude-points-haversine-formula

And then you need to iterate through all possibilities and take the
smallest distance.

For example:
> https://stackoverflow.com/questions/21279559/geolocation-closest-locationlat-long-from-my-position

Alternatively, if this is too slow (because of thousands/millions of
locations), there are algorithms for getting all points within a certain
lat-lon-range (e.g. as implemented in Solr, see
https://cwiki.apache.org/confluence/display/solr/Spatial+Search) but you
probably won't need those complexities.


However, in reality probably the distance is not the only factor to
choose which number is more appropriate, country borders / political
affinities often skew this. So you could also create a country/state
mapping (ie Sydney is responsible for Japan etc.).
