### ISSUE TITLE
External IP of this server error

### ISSUE THREAD

**Issue by lalop** [yellowtree/wp-geoip-detect#29]
I had an issue in developpment with the external ip detection.
I set the field in the setting so this work now but I don't understand why the plugin need this information since I'm using the local database Maxmind GeoIP Lite City

Thank you

**Comment by benjaminpick** [comment]
When you are on a local development server, the client IP your request
has is a local IP, e.g. 127.0.0.1. This IP is not in the local IP
database, because it does not contain any geolocation information.

To make testing easier, I have programmed the plugin to use the external
IP of the server instead. So it tries to connect to the internet and
asks predefined sites, which client IP the server has. So if it is not
connected to the internet, the lookup on these sites will time out.

**Comment by lalop** [comment]
This makes sense... 
thank you
