### ISSUE TITLE
ISO3 Support

### ISSUE THREAD

**Issue by andyinabox** [yellowtree/wp-geoip-detect#36]
Is there any support (or plan to support) ISO3 (3-digit) country codes? I know I can get the data from [country.io](http://country.io/data/) but it would be nice to have it built into the plugin.

**Comment by benjaminpick** [comment]
Hi,

the issue is not the data - the 3-letter-codes are also in the
GeoNames-DB which already is included in the plugin (/lib).

Rather the Maxmind lib Record Classes would need to be extended. This
could be done in this plugin (as it is unwrapping and re-wrapping the
data anyway) ... or better, upstream by Maxmind (the v1 version of the
API had 3-letter-codes).

So if you want to implement 3-letter-support, you can send me a pull
request or try to work it out with Maxmind. Due to time constraints I am
currently only bugfixing this plugin.

Greetings!

**Comment by benjaminpick** [comment]
I have added the 3-letter codes to the GeoNames data in 5550b04 . In theory, you can now access to them using this workaround: `$record->jsonSerialize()['country']['iso_code3']`. Obviously, it would be nicer to use something along `$record->country->isoCode3` but this would need a new class.

**Comment by andyinabox** [comment]
Great, thank you @benjaminpick !

**Comment by bhruge** [comment]
> I have added the 3-letter codes to the GeoNames data in [5550b04](https://github.com/yellowtree/geoip-detect/commit/5550b04b5a4d4af063ba190bbb2a06125df04437) . In theory, you can now access to them using this workaround: `$record->jsonSerialize()['country']['iso_code3']`. Obviously, it would be nicer to use something along `$record->country->isoCode3` but this would need a new class.

how to use in wordpress plugin?
