### ISSUE TITLE
inet_pton(): Unrecognized address  

### ISSUE THREAD

**Issue by stevesearer** [yellowtree/wp-geoip-detect#52]
My apologies on this somewhat open-ended question, but I've recently been getting the following PHP warning message and not certain where to start on troubleshooting:

     WARNING: wp-content/plugins/geoip-detect/geoip-detect-lib.php:257 - inet_pton(): Unrecognized address  

Any thoughts would be greatly appreciated!

Thank you,

**Comment by benjaminpick** [comment]
I am using inet_pton to normalize the IP formats (esp. with IPv6 the same IP can have different string representations ...) - always with an error-suppressing @ because it might be an invalid IP indeed. Probably this error-suppresing is disabled via php.ini at your host. Anyway, nothing to worry about. I will add a validity check for future versions.
